name: simple_counter
description: "A simple counter made to learn the Flutter programming language."
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.13.0

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
